server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  neo4j:
    uri: ${NEO_URI}
    authentication:
      username: ${NEO_USER}
      password: ${NEO_PASSWORD}

logging:
  level:
    root: INFO

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 50000000
  refresh-token-expiration: 86400000

# Expone el endpoint /actuator/health para el self-ping
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
